### ISSUE TITLE
execution de : vertx runMod org.entcore~infra~1.19.6 -conf ent-core.json & 

### ISSUE THREAD

**Issue by dgu123** [OPEN-ENT-NG/springboard-open-ent#3]
Bonjour

l execution de vertx runMod org.entcore~infra~1.19.6 -conf ent-core.json & donne : 

Error deploying pre-required module. 
java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.CommunityFacadeFactory, /home/coder/atos/springboard-open-ent/./data/tests/neo4j
    at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:143)
    at org.neo4j.kernel.impl.factory.CommunityFacadeFactory.newFacade(CommunityFacadeFactory.java:43)
    at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:108)
    at org.neo4j.graphdb.factory.GraphDatabaseFactory.newDatabase(GraphDatabaseFactory.java:129)
    at org.neo4j.graphdb.factory.GraphDatabaseFactory$1.newDatabase(GraphDatabaseFactory.java:117)
    at org.neo4j.graphdb.factory.GraphDatabaseBuilder.newGraphDatabase(GraphDatabaseBuilder.java:185)
    at fr.wseduc.neo4j.Neo4jEmbedded.<init>(Neo4jEmbedded.java:63)
    at fr.wseduc.neo4j.Neo4jPersistor.start(Neo4jPersistor.java:58)
    at org.vertx.java.platform.Verticle.start(Verticle.java:82)
    at org.vertx.java.platform.impl.DefaultPlatformManager$21.run(DefaultPlatformManager.java:1743)
    at org.vertx.java.core.impl.DefaultContext$3.run(DefaultContext.java:175)
    at org.vertx.java.core.impl.DefaultContext$3.run(DefaultContext.java:175)
    at org.vertx.java.core.impl.OrderedExecutorFactory$OrderedExecutor$1.run(OrderedExecutorFactory.java:92)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.NeoStoreDataSource@9c7805' was successfully initialized, but failed to start. Please see attached cause exception.
    at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:462)
    at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
    at org.neo4j.kernel.impl.transaction.state.DataSourceManager.start(DataSourceManager.java:112)
    at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
    at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
    at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:139)
    ... 15 more
Caused by: org.neo4j.kernel.impl.store.UnderlyingStorageException: Unable to open store file: /home/coder/atos/springboard-open-ent/./data/tests/neo4j/neostore.nodestore.db.labels
    at org.neo4j.kernel.impl.store.CommonAbstractStore.checkStorage(CommonAbstractStore.java:161)
    at org.neo4j.kernel.impl.store.CommonAbstractStore.initialise(CommonAbstractStore.java:102)
    at org.neo4j.kernel.impl.store.NeoStores.initialize(NeoStores.java:429)
    at org.neo4j.kernel.impl.store.NeoStores$StoreType$1.open(NeoStores.java:85)
    at org.neo4j.kernel.impl.store.NeoStores$StoreType$1.open(NeoStores.java:78)
    at org.neo4j.kernel.impl.store.NeoStores.openStore(NeoStores.java:422)
    at org.neo4j.kernel.impl.store.NeoStores.getOrCreateStore(NeoStores.java:467)
    at org.neo4j.kernel.impl.store.NeoStores.<init>(NeoStores.java:365)
    at org.neo4j.kernel.impl.store.StoreFactory.openNeoStores(StoreFactory.java:174)
    at org.neo4j.kernel.impl.store.StoreFactory.openAllNeoStores(StoreFactory.java:138)
    at org.neo4j.kernel.NeoStoreDataSource.buildNeoStore(NeoStoreDataSource.java:661)
    at org.neo4j.kernel.NeoStoreDataSource.start(NeoStoreDataSource.java:535)
    at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
    ... 20 more
Caused by: org.neo4j.io.pagecache.impl.FileLockException: Externally locked: /home/coder/atos/springboard-open-ent/./data/tests/neo4j/neostore.nodestore.db.labels
    at org.neo4j.io.pagecache.impl.SingleFilePageSwapper.acquireLock(SingleFilePageSwapper.java:209)
    at org.neo4j.io.pagecache.impl.SingleFilePageSwapper.<init>(SingleFilePageSwapper.java:160)
    at org.neo4j.io.pagecache.impl.SingleFilePageSwapperFactory.createPageSwapper(SingleFilePageSwapperFactory.java:64)
    at org.neo4j.io.pagecache.impl.muninn.MuninnPagedFile.<init>(MuninnPagedFile.java:95)
    at org.neo4j.io.pagecache.impl.muninn.MuninnPageCache.map(MuninnPageCache.java:357)
    at org.neo4j.kernel.impl.store.CommonAbstractStore.checkStorage(CommonAbstractStore.java:140)
    ... 32 more

cordialement,
david

**Comment by rdjedjig** [comment]
As tu bien configuré les propriétés de configuration neo4j de la manière suivante dans le fichier conf.properties ? : 

```
neo4jUri=http://localhost:7474
neo4jEmbedded=false  
```

Après avoir modifier le fichier conf.properties penses à lancer la commande
`gradle generateConf`

Avant de relancer ton springboard
`vertx runMod org.entcore~infra~1.19.6 -conf ent-core.json`

**Comment by dgu123** [comment]
Bon point maintenant j ai celle ci :

Error deploying pre-required module. 
java.lang.RuntimeException: Fail-fast during pool initialization
    at com.zaxxer.hikari.pool.BaseHikariPool.initializeConnections(BaseHikariPool.java:500)
    at com.zaxxer.hikari.pool.BaseHikariPool.<init>(BaseHikariPool.java:172)
    at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:61)
    at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:49)
    at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:78)
    at fr.wseduc.sql.SqlPersistor.start(SqlPersistor.java:34)
    at org.vertx.java.platform.Verticle.start(Verticle.java:82)
    at org.vertx.java.platform.impl.DefaultPlatformManager$21.run(DefaultPlatformManager.java:1743)
    at org.vertx.java.core.impl.DefaultContext$3.run(DefaultContext.java:175)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.postgresql.util.PSQLException: FATAL: no PostgreSQL user name specified in startup packet
    at org.postgresql.Driver$ConnectThread.getResult(Driver.java:361)
    at org.postgresql.Driver.connect(Driver.java:284)
    at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:57)
    at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:63)
    at com.zaxxer.hikari.pool.BaseHikariPool.addConnection(BaseHikariPool.java:396)
    at com.zaxxer.hikari.pool.BaseHikariPool.initializeConnections(BaseHikariPool.java:498)
    ... 11 more

**Comment by elbywan** [comment]
C'est la même avec postgresql :

```
sqlUrl=jdbc:postgresql://localhost:5432/[database]
sqlUsername=xxxx
sqlPassword=xxxx
```

Il faut créer une database, avec un utilisateur et un rôle dessus et paramétrer dans la conf.

**Comment by rdjedjig** [comment]
C'est pas [schema] mais [database] qu'il faut renseigner. 
Ton utilisateur doit avoir au moins les droits de création de schéma sur ta base de donnée pour que cela fonctionne. Pour faire simple tu peux lui donner le role de super utilisateur sur ton poste de développeur.
