### ISSUE TITLE
Error during the starting up of the springboard 

### ISSUE THREAD

**Issue by dgu123** [OPEN-ENT-NG/springboard-open-ent#5]
org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "pg_extension_name_index"
  Detail: Key (extname)=(unaccent) already exists.
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2198)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1927)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:561)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:405)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:397)
        at com.zaxxer.hikari.proxy.StatementProxy.execute(StatementProxy.java:83)
        at com.zaxxer.hikari.proxy.StatementJavassistProxy.execute(StatementJavassistProxy.java)
        at fr.wseduc.sql.SqlPersistor.raw(SqlPersistor.java:113)
        at fr.wseduc.sql.SqlPersistor.raw(SqlPersistor.java:101)
        at fr.wseduc.sql.SqlPersistor.doTransaction(SqlPersistor.java:171)
        at fr.wseduc.sql.SqlPersistor.handle(SqlPersistor.java:61)
        at fr.wseduc.sql.SqlPersistor.handle(SqlPersistor.java:17)
        at org.vertx.java.core.eventbus.impl.DefaultEventBus$11.run(DefaultEventBus.java:963)
        at org.vertx.java.core.impl.DefaultContext$3.run(DefaultContext.java:175)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

any idea why it is happening during the installation ?
solving it is not an issue really.
Regards
david

**Comment by rdjedjig** [comment]
Bonjour,

Une commande de création d'extension "unaccent" doit être exécutée.

Dans le répertoire mods/ de ton springboard tu peux la chercher :
 `find -iname *.sql | xargs grep -irn unaccent`

C'est bloquant pour le reste de l'exécution sachant que l'extension est déjà disponible.
