### ISSUE TITLE
connecting to 129.181.25.238:32768 ??? 

### ISSUE THREAD

**Issue by dgu123** [OPEN-ENT-NG/springboard-open-ent#6]
Dear Team,

an another exception  :
Registering notification : mindmap.share
Successfully registered widgets for application Maxicours
Registering notification : pages.shared
Error registering application Portal
Registering notification : userbook.delete-email
Registering notification : rbs.booking-validated
Registering notification : rbs.booking-deleted
Registering notification : rbs.periodic-booking-created
Registering notification : rbs.booking-updated
Registering notification : rbs.resource-available
Registering notification : rbs.booking-created
Error registering application FakeSSO
Registering notification : rbs.periodic-booking-updated
Registering notification : rbs.periodic-booking-deleted
Registering notification : rbs.booking-refused
Registering notification : rbs.resource-unavailable
Successfully registered widgets for application Signets
Exception in Java verticle
io.netty.channel.ConnectTimeoutException: connection timed out: /129.181.25.238:32768
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:214)
        at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:123)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:370)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
        at java.lang.Thread.run(Thread.java:745)

Registering notification : pages.shared

could you explain to me where is store this address and why??

regards
david

**Comment by rdjedjig** [comment]
Bonjour,

Il y a un problème de configuration dans l'application shareBigFile.

```
find -iname *.json | xargs grep -irn 129.181.25.238

deployments/sharebigfiles/conf.json.template:18:              "uri": "http://129.181.25.238:32768",
```

Cette propriété n'est pas paramétrisée.

**Comment by rdjedjig** [comment]
@pjallet Je t'affecte cette demande. ShareBigFile est une application maintenue par Atos.
